name: binder-base
channels:
  - conda-forge
  - default
dependencies:
  - jupyterlab
  - ipykernel
  - ipywidgets
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - altair
  - seaborn
  - plotly
  - ipympl
  - ipyleaflet
  - pythreejs
  - empymod
  - localtileserver
  - shapely
  - folium
  - colorcet
  - cmocean
  - jupyter-server-proxy
  - gdal
  - curvenote
  - pip
  - pip:
      - geoana
