name: base
channels:
  - conda-forge
  - default
dependencies:
  - jupyterlab
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - altair
  - seaborn
  - plotly
  - ipykernel
  - ipywidgets
  - ipympl
  - ipyleaflet
  - ipythreejs
  - pip
  - pip:
      - pyviz
